### ISSUE TITLE
Question about powerCurve function: where does it use the random number generator?

### ISSUE THREAD

**Issue by bast** [pitakakariki/simr#270]
## This is a question not an issue

This issue is more of a question/suggestion. It does not report a problem. If I ask this in the wrong place, can you please point me to a better place?

## My question in short

Where does the code use the random number generator when calling `powerCurve`? I have looked through the code but I am not sure I can locate it. Very likely I misunderstood something.

## Longer question

In a function call like this one:
```R
result = powerCurve(data, fixed('x'), along = 'g', breaks = 4, nsim = 100, seed = 123)
```
I send in the seed (in this case 123) and run 100 simulations. The seed is initialized inside the code (I found that part) and later it must be used somewhere. But I am not sure where precisely the random number generator is used.

## Context for my question and my goal

What I would like to do is to "parallelize" a function call which takes very long time by reducing `nsim` from say 100 to 1 or 10 and moving the loop over nsim "outside" of the function and later recombine the independent results. So I still want to set a seed but all individual simulations should use the random number generator with the same offset as in `nsim = 100`. So I will somehow need to pass that offset. It is possible that what I try here does not make any sense :-) I am trying to help somebody to reduce the total runtime of a computation by splitting the problem up into many independent computations which we can run on many cores. But we still want the same result.

Any hint will be very appreciated. Also an honest "this does not make sense" is very appreciated. Thank you!

**Comment by pitakakariki** [comment]
The rng happens over in lme4 - `doSim` is a wrapper around `lme4::simulate.formula`. That probably won't help you with your problem though.

I think what you want is a "Random Number Stream", see e.g. https://www.rdocumentation.org/packages/parallel/versions/3.6.2/topics/RNGstreams

You would use the stream to generate however many "sub-stream" seeds you need, and then in theory pass these on to simr's `nsim` argument. I think you'll need to maybe fork simr so that its `set.seed` call takes a `kind` argument.

**Comment by bast** [comment]
Thanks a lot for the useful leads! I will try that on a fork.

I will close this issue but I will report how it went and if it works out we can discuss whether this could be useful for more people.
